<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7a5c6705e45f2206281c7c1b7170796f
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7a5c6705e45f2206281c7c1b7170796f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7a5c6705e45f2206281c7c1b7170796f::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
